--[[
    ~ pm. A package manager by Hugo Coto.
]] --

-- Add ~/.config/pm/ to the path
package.path = package.path .. ";" .. os.getenv("HOME") .. "/.config/pm/?.lua"

-- System configuration
System = {
    build = { path = os.getenv("HOME") .. "/.local/share/pm/cache/" }, -- Build path
    bin = { path = os.getenv("HOME") .. "/.local/share/pm/bin/" },     -- Bin path
}

local ur = require 'ur'

--[[
    Package possible fields:
    - url: url to the file
    - name: name of the file downloaded from url
    - build: build script that generates the artifact
    - artifact: name of the executable generated by the build script
    - last_modified_cmd: custom command to get Last-Modified date
]] --
Packages = {
    {
        -- pm bootstraping. Keep pm updated.
        url = "https://github.com/hugoocoto/pm/releases/download/nightly/pm-x86_64.AppImage",
        build = "chmod +x pm",
        name = "pm",
    },

    {
        url = "https://github.com/hugoocoto/wallpapers/releases/download/latest/wallpaper",
        build = "chmod +x wallpaper",
        name = "wallpaper",
    },

    ur.Fetch { user = "hugoocoto", file = "nvim-nightly/nvim.lua" },
    ur.Fetch { user = "hugoocoto", file = "helium/helium.lua" },

    ur.Github { user = "hugoocoto", repo = "dv" },
    ur.Github { user = "hugoocoto", repo = "todo" },
    ur.Github { user = "hugoocoto", repo = "vicel", cmd = "make release" },
    ur.Github { user = "hugoocoto", repo = "fetch" },
    ur.Github { user = "hugoocoto", repo = "eqnx" },
    ur.Github { user = "hugoocoto", repo = "yaci" },
    ur.Github { user = "hugoocoto", repo = "zrun", cmd = "zig build", artifact = "zig-out/bin/zrun" },
    ur.Github { user = "hugoocoto", repo = "pdfjoin", cmd = "chmod +x pdfjoin" },
    ur.Github { user = "hugoocoto", repo = "b", cmd = "make b && make desktop-entry" },
    ur.Github { user = "hugoocoto", repo = "tetris" },
    ur.Github { user = "hugoocoto", repo = "st" },
}
