--[[
    ~ pm. A package manager by Hugo Coto.
]] --

-- Add ~/.config/pm/ to the path
package.path = package.path .. ";" .. os.getenv("HOME") .. "/.config/pm/?.lua"

-- Build path
Build = {
    path = os.getenv("HOME") .. "/.local/share/pm/cache/"
}

-- Bin path
Bin = {
    path = os.getenv("HOME") .. "/.local/share/pm/bin/"
}

--[[
    Package possible fields:
    - url: url to the file
    - name: name of the file downloaded from url
    - build: build script that generates the artifact
    - artifact: name of the executable generated by the build script
    - last_modified_cmd: custom command to get Last-Modified date
]] --
Packages = {
    {
        -- pm bootstraping. Keep pm updated.
        url = "https://github.com/hugoocoto/pm/releases/download/nightly/pm.tar.gz",
        build = "tar -xzf pm.tar.gz && make",
        artifact = "pm",
    },
    require 'nvim',
}
