font_family      "Iosevka NFM"
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 24.0

disable_ligatures always # never

cursor none # reverse | or color
# cursor_text_color background

cursor_shape block
cursor_shape_unfocused block
cursor_blink_interval 0 # disabled

progress_bar bottom

mouse_hide_wait -1 # hide when typing

url_color #0087bd
url_style curly

copy_on_select clipboard
sync_to_monitor yes
enable_audio_bell no

active_border_color #00ff00 # The color for the border of the active window
inactive_border_color #cccccc # The color for the border of inactive windows.
bell_border_color #ff5a00 # The color for the border of inactive windows in which a bell has occurred.
