wallpaper { 
    monitor = eDP-1
    path = /home/hugo/Pictures/art_57.png
    fit_mode = cover
}

wallpaper { 
    monitor = HDMI-A-1
    path = /home/hugo/Pictures/art_57.png
    fit_mode = cover
}

#disable splash text rendering over the wallpaper
splash = false

#fully disable ipc
ipc = false
