wallpaper { 
    monitor = eDP-1
    path = /home/hugo/Pictures/Green_Wheat_Fields_Auvers.jpg
    fit_mode = cover
}

wallpaper { 
    monitor = DP-1
    path = /home/hugo/Pictures/Green_Wheat_Fields_Auvers.jpg
    fit_mode = cover
}

wallpaper { 
    monitor = HDMI-A-1
    path = /home/hugo/Pictures/Green_Wheat_Fields_Auvers.jpg    
    fit_mode = cover
}

#disable splash text rendering over the wallpaper
splash = false

#fully disable ipc
ipc = false
